### ISSUE TITLE
Cannot open Mac application: it is 'damaged'

### ISSUE THREAD

**Issue by axello** [DeepSea-Developments/DeepDeck.Web#2]
Hi 
I downloaded `DeepDeck-0.5.3-arm64` and opened it on my MacBook M1 with Ventura 13.3.

I could not open the app, as the OS complained it is 'damaged'. Probably just a certificate or code-signing error.
<img width="372" alt="Screenshot 2023-05-26 at 16 01 38" src="https://github.com/DeepSea-Developments/DeepDeck.Web/assets/149241/43598832-9031-4428-be08-412f3ebf0662">

**Comment by electronick-co** [comment]
Hi! please use the latest release of DeepDeck. It contains the webserver in the DeepDeck and not as an external device! Also, give a look to the new programming tool https://github.com/DeepSea-Developments/DeepDeck.programmer/releases
